### ISSUE TITLE
Device schema cannot be used in OpenAPI 3.0 projects since const and version keywords are not supported

### ISSUE THREAD

**Issue by christian-knecht** [smart-data-models/dataModel.Device#23]
I cannot use the Device schema in my express-openapi project since version: 0.0.5 and batteryLevel const -1 are not supported keywords in OpenAPI 3.0 projects.

For batteryLevel I suggest to use following scheme:
``` yaml
batteryLevel:
  description: 'Device battery level. It must be equal to 1.0 when battery is full. 0.0 when battery is empty. -1 when transiently cannot be determined.'
  maximum: 1
  minimum: -1
  type: number
  default: -1
```
Could you please fix that?

**Comment by jason-fox** [comment]
This is the current schema.json 
 
```json
 "batteryLevel": {
          "description": "Property. Model:'https://schema.org/Number'. Device battery level. It must be equal to 1.0 when battery is full. 0.0 when battery is empty. -1 when transiently cannot be determined.",
          "oneOf": [
            {
              "type": "number",
              "minimum": 0,
              "maximum": 1
            },
            {
              "type": "number",
              "const": -1
            }
          ]
        }
```
This is then autogenerated as the following model.yaml

```yml
batteryLevel:
      description: 'Device battery level. It must be equal to 1.0 when battery is full. 0.0 when battery is empty. -1 when transiently cannot be determined.'
      oneOf:
        - maximum: 1
          minimum: 0
          type: number
        - const: -1
          type: number
      x-ngsi:
        model: https://schema.org/Number
        type: Property
```

According to https://swagger.io/docs/specification/data-models/keywords/

> The following are **Unsupported Keywords** within Open API:
>
>
> -  `$schema`
> -  `additionalItems`
> -  `const`
> -  `contains`
> -  `dependencies`
> -  `id`
> -  `$id`
> -  `patternProperties`
> -  `propertyNames`

So the generator  schema.json => model.yaml needs to tweak those values - either translate as suggested or ignore `const` altogether

**Comment by jason-fox** [comment]
Annoyingly Open API only allows a single discrete range, so:

```
if const > maximum  then maximum = const
if const < minimum  then minimum = const
```

is the only way to go. Setting a `default` as described in the [original issue description](https://github.com/smart-data-models/dataModel.Device/issues/23#issue-1038945710) makes sense, but can only be the case if only a single `const` is allowed outside of a range.

**Comment by jason-fox** [comment]
Taking the latest `Device` and pasting  it directly into https://editor.swagger.io/ gives me two errors:

```yaml
Device:
  description: >- 
    An apparatus (hardware + software + firmware) intended to accomplish a particular task 
    (sensing the environment, actuating, etc.).
  modelTags: ""
  properties:
    address:
      type: object
  required:
    - id
    - type
    - controlledProperty
  type: object
  version: 0.0.6
```


![Screenshot 2021-11-01 at 10 03 34](https://user-images.githubusercontent.com/3439249/139648057-e95c8a95-ca4f-475c-addb-48e7b5d4fa0b.png)

I assume `version` and `modelTags` are custom elements, and require the `x-` prefix: 


```yaml
Device:
  description: >-
    An apparatus (hardware + software + firmware) intended to accomplish a
    particular task  (sensing the environment, actuating, etc.).
  x-modelTags: ''
  properties:
    address:
      type: object
  required:
    - id
    - type
    - controlledProperty
  type: object
  x-version: 0.0.6
```

**Comment by christian-knecht** [comment]
The suggested solutions by @jason-fox seems to be a great solution for the property batteryLevel:
```yaml
batteryLevel:
  description: >-
    Device battery level. It must be equal to 1.0 when battery is full. 0.0 when
    battery is empty. -1 when transiently cannot be determined.
  oneOf:
    - maximum: 1
      minimum: 0
      type: number
    - maximum: -1
      minimum: -1
      type: number
```
The x-model-tags and  x-version seems to be "fixed" already in the current version. Thanks!
